services:
  - type: web
    name: raadhya-backend-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_SECRET_KEY
        value: Raadhya00001
      - key: SESSION_SECRET_KEY
        value: ANOTHER_VERY_LONG_SECRET_KEY
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: roject_root_db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: roject_root_db
          property: connectionString

databases:
  - name: roject_root_db
    plan: free
    databaseName: roject_root_db
    user: roject_root_db_user
